Repository CCExtractor/taskwarrior-flutter, pull requests merged in 2022-10, with the labels that each got.

#9 Feat: #8 (UI change for no name)
  lib/widgets/addTask.dart
Labels: hacktoberfest, hacktoberfest-accepted

#17 UI improvement in the Profile Page
  lib/views/profile/profile.dart
  lib/widgets/profilefunctions/selectprofile.dart
Labels: hacktoberfest, hacktoberfest-accepted, lkg

#20 Added Feature to change between dark and bright mode of home screen
  lib/services/task_list_tem.dart
  lib/views/home/home.dart
  lib/widgets/buildTasks.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, lkg

#30 Add dark mode in drawer and minor fixes
  lib/views/home/home.dart
  lib/widgets/buildTasks.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, lkg, UI

#32 Theme consistency
  .vscode/settings.json
  lib/config/app_settings.dart
  lib/drawer/filter_drawer.dart
  lib/drawer/nav_drawer.dart
  lib/services/task_details.dart
  lib/views/home/home.dart
  lib/views/profile/profile.dart
  lib/widgets/addTask.dart
  lib/widgets/buildTasks.dart
  lib/widgets/profilefunctions/manageprofile.dart
  lib/widgets/profilefunctions/selectprofile.dart
  lib/widgets/project_filter.dart
  lib/widgets/tag_filter.dart
  lib/widgets/taskdetails/dateTimePicker.dart
  lib/widgets/taskdetails/description_widget.dart
  lib/widgets/taskdetails/priority_widget.dart
  lib/widgets/taskdetails/status_widget.dart
  lib/widgets/taskdetails/tags_widget.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, feature, lkg, UI

#34 [Fix] - Icon colour of Add task
  lib/views/home/home.dart
  lib/widgets/addTask.dart
Labels: enhancement, UI

#36 [BUG-FIX] Invalid date format in task details
  lib/services/task_details.dart
  lib/widgets/addTask.dart
  lib/widgets/taskdetails/dateTimePicker.dart
Labels: bug, hacktoberfest, hacktoberfest-accepted

#39 snackbars
  lib/services/task_details.dart
  lib/views/profile/profile.dart
  lib/widgets/addTask.dart
  lib/widgets/profilefunctions/deleteprofiledialog.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, lkg

#45 Fixed #38
  lib/widgets/addTask.dart
  pubspec.yaml
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#47 fixed #44
  lib/taskserver/configure_taskserver.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, lkg

#48 Clear search on pressing enter
  lib/views/home/home.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, feature
